config/routes.rb
Rails.application.routes.draw do
  resource :session
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  resources :skeets do
    post "share", on: :collection
    get "search_actors", on: :collection
  end
  mount MissionControl::Jobs::Engine, at: "/jobs"
  root "skeets#index"
end

# Adding mission control jobs
# bin/rails credentials:edit <- Gen creds file
# Or bin/rails mission_control:jobs:authentication:configure

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bsky_user.rb
class BskyUser < ApplicationRecord
  encrypts :app_password
  has_many :skeets
end

app/models/skeet.rb
class Skeet < ApplicationRecord
  enum :status, { draft: "draft", scheduled: "scheduled", published: "published" }, default: :draft
  belongs_to :bsky_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private

  def authenticated?
    session[:identifier].present?
  end

  def require_authentication
    authenticated? || request_authentication
  end

  def request_authentication
    session[:return_to_after_authenticating] = request.url
    redirect_to new_session_path
  end

  def after_authentication_url
    session.delete(:return_to_after_authenticating) || root_url
  end

  def start_new_session_for(identifier:, app_password:)
    session[:identifier] = identifier
    session[:app_password] = app_password
    session[:user_agent] = request.user_agent
    session[:ip_address] = request.remote_ip
    session[:created_at] = Time.current
  end

  def terminate_session
    session.clear
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  def new
  end

  def create
    start_new_session_for(identifier: user_params[:identifier], app_password: user_params[:app_password])
    redirect_to after_authentication_url
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end

  private

  def user_params
    params.permit(:identifier, :app_password)
  end
end

app/controllers/skeets_controller.rb
require "bsky_parser"

class SkeetsController < ApplicationController
  BASE_URL = "https://bsky.social"
  def index
    @drafts = Skeet.draft.order(created_at: :desc)
    # Identifier must be without the @.

    # https://docs.bsky.app/blog/create-post#authentication
    # > com.atproto.server.createSession API endpoint returns a session object containing two API tokens: an access token (accessJwt)
    # > which is used to authenticate requests but expires after a few minutes
    # Always reauthenticate when you get back to this page.
    response = conn.post("/xrpc/com.atproto.server.createSession") do |req|
      req.headers["Content-Type"] = "application/json"
      req.body = JSON.generate({
        identifier: session[:identifier],
        password: session[:app_password]
      })
    end
    # TODO: Configurable timezone
    Time.zone = "Eastern Time (US & Canada)"
    @current_datetime = Time.zone.now
    session[:user] = JSON.parse(response.body)
  end

  def create
    content = params[:content]
    # TODO: Handle blank submits (client side validation)
    return redirect_to root_url if content.blank?
    commit_action = params[:commit]
    return redirect_to root_url if content.length > 300 && commit_action == "Post"

    user = BskyUser.create(identifier: session[:identifier], app_password: session[:app_password])
    skeet = user.skeets.create(content: content)
    case commit_action
    when "Save Draft"
      skeet.draft!
    when "Post"
      skeet.published!
      post_to_bsky(content)
    when "Schedule"
      Time.zone = "Eastern Time (US & Canada)"
      scheduled_at = params["scheduled_at"]
      scheduled_datetime = Time.zone.local(
        scheduled_at["datetime(1i)"],
        scheduled_at["datetime(2i)"],
        scheduled_at["datetime(3i)"],
        scheduled_at["datetime(4i)"],
        scheduled_at["datetime(5i)"]
      )
      # Handle error
      skeet.scheduled!
      SkeetSchedulerJob.set(wait_until: scheduled_datetime).perform_later(skeet_id: skeet.id)
      return redirect_to root_url
    end

    redirect_to root_url
  end

  def share
    skeet = Skeet.find(params[:skeet_id])
    post_to_bsky(skeet.content)
    # TODO: Shouldn't assume that the post to bsky worked
    skeet.published!
    redirect_to root_url
  end

  def search_actors
    resp = public_conn.get("/xrpc/app.bsky.actor.searchActorsTypeahead", { q: params[:q], limit: 8 })
    puts JSON.parse(resp.body)
    @actors = JSON.parse(resp.body)["actors"]

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.update("mentions-dropdown", partial: "skeets/actor_suggestions", locals: { actors: @actors }) }
    end
  end

  private

  def conn
    @conn ||= Faraday.new(url: BASE_URL) do |f|
      f.request :json
    end
  end

  def public_conn
    @public_conn ||= Faraday.new(url: "https://public.api.bsky.app") do |f|
      f.request :json
    end
  end

  def post_to_bsky(content)
    current_time = Time.now.utc.strftime("%Y-%m-%dT%H:%M:%S.%3NZ")
    processed_content, facets = BskyParser.parse(content)
    request_body = {
      repo: session[:user]["did"],
      collection: "app.bsky.feed.post",
      record: {
        text: processed_content,
        facets: facets,
        createdAt: current_time,
        "$type": "app.bsky.feed.post"
      }
    }

    conn.post("/xrpc/com.atproto.repo.createRecord") do |req|
      req.headers["Content-Type"] = "application/json"
      req.headers["Authorization"] = "Bearer #{session[:user]["accessJwt"]}"
      req.body = JSON.generate(request_body)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Bis Kay" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/biskay.png" type="image/png">
    <link rel="apple-touch-icon" href="/biskay.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto max-w-screen-sm mt-6 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/skeets/_actor_suggestions.html.erb
<ul role="listbox" class="py-1">
  <% actors.each_with_index do |actor, index| %>
    <li role="option"
        class="px-4 py-2 hover:bg-gray-100 cursor-pointer flex items-center"
        data-action="click->skeets#selectUser"
        data-user-handle="<%= actor["handle"] %>">
      <img src="<%= actor["avatar"] %>"
           alt="<%= actor["displayName"] %>"
           class="w-8 h-8 rounded-full mr-3">
      <div>
        <div class="font-medium"><%= actor["displayName"] %></div>
        <div class="text-sm text-gray-500">@<%= actor["handle"] %></div>
      </div>
    </li>
  <% end %>
</ul>

app/views/skeets/index.html.erb
<h1 class="text-4xl mb-8 font-extrabold block">Biskay</h1>

<%= form_tag "/skeets", data: { controller: "skeets" } do %>
  <div class="relative">
    <%= text_area_tag :content, nil, rows: 5, class: "block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6", data: { action: "skeets#onInput  keydown->skeets#onKeydown", skeets_target: "skeet" } %>
    <div data-skeets-target="dropdown" id="mentions-dropdown" class="absolute left-0 w-full mt-1 bg-white rounded-md shadow-lg max-h-60 overflow-y-auto z-50"></div>
    <div data-skeets-target="counter" class="absolute bottom-2 right-2 text-sm text-gray-500">
      300 characters remaining
    </div>
  </div>
  <div class="mt-6 flex items-center justify-end  gap-x-1">
    <%= datetime_select :scheduled_at, :datetime, { default: @current_datetime, ampm: true, order: [:day, :month, :year] }, class: "border border-gray-300 rounded-sm focus:ring-blue-500 focus:border-blue-500 p-1", data: { action: "skeets#checkScheduledDate", skeets_target: "datepicker" } %>
  </div>
  <div class="mt-3 flex items-center justify-end gap-x-1">
    <%= submit_tag "Save Draft", class: "cursor-pointer rounded-sm border-gray-200 hover:bg-gray-100 hover:text-blue-700 border px-3 py-2 text-sm font-semibold text-gray-900 shadow-xs focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    <%= submit_tag "Post", class: "cursor-pointer rounded-sm bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", data: { skeets_target: "submit" } %>
  </div>
<% end %>

<h2 class="text-3xl mb-8 font-extrabold block">Drafts</h2>
<% @drafts.each do |draft| %>
  <div>
    <p class="border border-gray-200 rounded-sm p-3 mb-2">
      <%= draft.content%>
    </p>
    <div class="mt-3 flex items-center justify-end gap-x-1">
      <%= button_to "Share now", share_skeets_path, params: { skeet_id: draft.id },class: "cursor-pointer rounded-sm bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    </div>
  </div>
<% end %>